version: '3.8'
services:
  goapp:
    image: goapp:1.0
    build: 
      context: jobtrack-api
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
      GO_PORT: ${GO_PORT}
      GO_ENV: ${GO_ENV}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./.env:/app/.env
    env_file:
    - .env

  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    env_file:
    - .env

  client:
    image: client:latest
    build:
      context: ./jobtrack-cli
      dockerfile: Dockerfile
    depends_on:
      - goapp
    environment:
      API_URL: ${API_URL}

  frontend:
    build:
      context: ./jobtrack-frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - goapp
    env_file:
    - .env